[package]
name = "apoapsis_multiboot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
clap = "4.2.2"
socket2 = "0.5.2"
